version: "3.8"

services:
  # 1. The Database (New!)
  postgres:
    image: postgres:15-alpine
    container_name: pizza-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: pizza_password
      POSTGRES_DB: pizza_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pizza-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizza_user -d pizza_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. The Broker
  redis:
    image: redis:alpine
    container_name: pizza-redis
    ports:
      - "6380:6379"
    networks:
      - pizza-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 3. The Producer (API)
  order-api:
    build: ./order-api
    container_name: pizza-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Connects to 'postgres' service on port 5432
      - DATABASE_URL=postgresql://pizza_user:pizza_password@postgres:5432/pizza_db?schema=public
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - pizza-net

  # 4. The Consumer (Worker)
  kitchen-worker:
    build:
      context: .
      dockerfile: kitchen-worker/Dockerfile
    container_name: pizza-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://pizza_user:pizza_password@postgres:5432/pizza_db?schema=public
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - pizza-net

  # 5. Run Prisma migrations (one-off)
  migrate:
    build:
      context: ./order-api
      target: builder
    container_name: pizza-migrate
    command: sh -c "npx prisma migrate deploy --schema=prisma/schema.prisma"
    environment:
      - DATABASE_URL=postgresql://pizza_user:pizza_password@postgres:5432/pizza_db?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pizza-net

networks:
  pizza-net:
    driver: bridge

volumes:
  pg_data:
