apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  type: LoadBalancer # <--- The Magic Door to the outside world
  ports:
    - port: 80 # Port exposed to the world
      targetPort: 3000 # Port inside the container
  selector:
    app: order-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 2 # High Availability!
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: pizza-api:latest
          imagePullPolicy: Never # <--- Important for Minikube
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis" # Matches the Service Name from redis.yaml
            - name: REDIS_PORT
              value: "6379"
            - name: DATABASE_URL
              value: "postgresql://pizza_user:pizza_password@postgres:5432/pizza_db?schema=public"
